# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Test-Labeler
on: 
  pull_request_target:
    types: [opened]

jobs:
  label:
    name: add label to new PRs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v3
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |
          // Get PR description
          const msg = context.payload.pull_request.title;
          console.log(Object.keys(context.payload.pull_request)[17]);
          console.log(Object.keys(context.payload.pull_request)[16]);
          console.log(Object.keys(context.payload.pull_request)[15]);
          
          class AdaPullRequest 
            constructor(label, column_id) {
              this.label = label;
              this.column_id = column_id;
            }

            addLabel() {
              github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [this.label] 
              })
            }

            addToProjectBoard() {
              github.projects.createCard({
                column_id: this.column_id,
                content_type: 'PullRequest',
                content_id: context.payload.pull_request.id
              })
            }
          }
          
          if(msg) {
            const inDevelopment = msg.includes("In Development");
            
            if(inDevelopment) {
              const developmentPullRequest = new AdaPullRequest("needs input", 11889953)
              developmentPullRequest.addLabel();
              developmentPullRequest.addToProjectBoard();
            } else {
              const generalPullRequest = new AdaPullRequest("ready for review", 11886851)
              generalPullRequest.addLabel();
              generalPullRequest.addToProjectBoard();
            }
          } 
